### ISSUE TITLE
how to connect all the components

### ISSUE THREAD

**Issue by Mikimimi** [bbasil2012/SSLAC16#3]
Hi bbasil,

do you have schematic how to connect all the components?

Can sslac16 control meanwell HLG-600H-15A constant current power supplies with PWM?
I would like to control 3 channels of LED with 120W per channel.
My idea was to buy three power supplies that are pwm dimmable and to use this kind of controller to dimm them.
Thank you

Mislav

**Comment by bbasil2012** [comment]
https://github.com/bbasil2012/SSLAC16/blob/main/docs/shematic.pdf

I have no experience of using this driver :(
but it is very interesting :)
I would advise to use optocoupler (pc817 for example) to control this driver
http://akizukidenshi.com/download/PC817C.pdf
anode - PWM pin SSLAC borad (PCA9685 board)
cathode - Ground pin SSLAC board (PCA9685 board)
emiter - DIM+ pin MW driver
collector - DIM- pin MV driver

WBR Basil
