### ISSUE TITLE
Export current configuration

### ISSUE THREAD

**Issue by ElectricImpossible** [bbasil2012/SSLAC16#4]
Two hours after getting the hardware I managed to get a working prototype!

Could I suggest that an export of the current times be implemented. This would help if I am altering the firmware between different projects

**Comment by bbasil2012** [comment]
Hi.

Try https://github.com/bbasil2012/SSLAC16/blob/main/tools/save_load.html - simple tools for save and load "daily schedule" from/to text file

**Comment by ElectricImpossible** [comment]
Impressive, just what I was looking for.

I downloaded the updated package, then uploaded the save_load.html via setuphw.html page.
I altered the IP to the devices IP (which is on my SSID) and then hit the "to load" button.

Config saved!
